# Generated by Django 2.1.7 on 2020-05-08 12:23

from django.db import migrations, models
import django.db.models.deletion
import utils.file_upload
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('average_rating', models.PositiveIntegerField(default=0, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('avatar', models.ImageField(default='noavatar.png', null=True, upload_to=utils.file_upload.professor_path, verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('review', models.TextField(default='', verbose_name='Отзыв')),
                ('value', utils.models.IntegerRangeField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('На модерации', 'На модерации'), ('Принят', 'Принят'), ('Отказан', 'Отказан')], default='На модерации', max_length=100, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Оценка преподавателя',
                'verbose_name_plural': 'Оценки преподавателя',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_proof_data', models.TextField(blank=True, verbose_name='Текстовое доказательство')),
                ('user_proof_file', models.FileField(blank=True, upload_to='', verbose_name='Файловое доказательство')),
                ('status', models.CharField(choices=[('На модерации', 'На модерации'), ('Принят', 'Принят'), ('Отказан', 'Отказан')], default='На модерации', max_length=50, verbose_name='Статус')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='api.ProfessorReview')),
            ],
            options={
                'verbose_name': 'Заявка на действительность отзыва',
                'verbose_name_plural': 'Заявки на действильность отзыва',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название предмета')),
                ('abbreviation', models.CharField(blank=True, max_length=300, null=True, verbose_name='Аббревиатура')),
                ('professors', models.ManyToManyField(blank=True, related_name='subjects', to='api.Professor', verbose_name='Преподаватели этого предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('abbreviation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Аббревиатура')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(default='noimage.png', max_length=1000, null=True, upload_to=utils.file_upload.university_path, verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='university',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='api.University'),
        ),
    ]
