# Generated by Django 2.1.7 on 2020-03-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique_for_month=True, verbose_name='Email')),
                ('review', models.CharField(max_length=1000, verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Оценка')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='api.Professor', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Оценка преподавателя',
                'verbose_name_plural': 'Оценки преподавателя',
                'ordering': ['-timestamp'],
            },
        ),
    ]
