# Generated by Django 2.1.7 on 2020-05-08 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professorreview',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Professor', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(to='api.University', verbose_name='Университеты в котором он преподает'),
        ),
    ]
