# Generated by Django 2.1.7 on 2020-05-08 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200508_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorreview',
            name='email',
        ),
        migrations.AddField(
            model_name='professorreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='professor_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
