# Generated by Django 2.1.7 on 2020-03-17 16:45

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200317_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorrating',
            name='rating',
        ),
        migrations.AddField(
            model_name='professorrating',
            name='value',
            field=utils.models.IntegerRangeField(default=0),
        ),
    ]
