# Generated by Django 2.1.7 on 2020-05-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200508_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(blank=True, to='api.University', verbose_name='Университеты в котором он преподает'),
        ),
    ]
