# Generated by Django 2.1.7 on 2020-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200508_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorreview',
            name='review',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
