# Generated by Django 2.1.7 on 2020-03-17 16:54

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_professorrating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorrating',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оценка преподавателя', 'verbose_name_plural': 'Оценки преподавателя'},
        ),
        migrations.RenameField(
            model_name='professorrating',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='professorrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='professorrating',
            name='value',
            field=utils.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='professorrating',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
    ]
