# Generated by Django 2.1.7 on 2020-05-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200508_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingapplication',
            name='status',
        ),
    ]
