# Generated by Django 2.1.7 on 2020-05-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ratingapplication_is_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingapplication',
            old_name='is_new',
            new_name='is_viewed',
        ),
    ]
