# Generated by Django 2.1.7 on 2020-03-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200317_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='average_rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='professor',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='professorrating',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Professor', verbose_name='Преподаватель'),
        ),
    ]
