# Generated by Django 2.1.7 on 2020-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200508_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingapplication',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Рассмотрен?'),
        ),
    ]
