# Generated by Django 2.1.7 on 2020-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200317_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='universities',
            field=models.ManyToManyField(to='api.University', verbose_name='Университеты в котором он преподает'),
        ),
    ]
