# Generated by Django 2.1.7 on 2020-05-13 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200508_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв преподавателю', 'verbose_name_plural': 'Отзывы преподавателю'},
        ),
        migrations.AddField(
            model_name='university',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='professorreview',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
