# Generated by Django 2.1.7 on 2020-03-17 17:47

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200317_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='', upload_to=utils.file_upload.university_path, verbose_name='Лого'),
        ),
    ]
