# Generated by Django 2.1.7 on 2020-03-17 17:51

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_university_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='settings.MEDIA_ROOT/noimage.png', upload_to=utils.file_upload.university_path, verbose_name='Лого'),
        ),
    ]
