# Generated by Django 2.1.7 on 2020-05-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200513_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorreview',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Subject'),
        ),
    ]
