# Generated by Django 2.1.7 on 2020-05-14 10:02

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_professorreview_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='nologo.png', max_length=1000, null=True, upload_to=utils.file_upload.university_path, verbose_name='Лого'),
        ),
    ]
