# Generated by Django 2.1.7 on 2020-03-17 18:19

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200317_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='avatar',
            field=models.ImageField(default='noimage.png', upload_to=utils.file_upload.professor_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='noimage.png', upload_to=utils.file_upload.university_path, verbose_name='Лого'),
        ),
    ]
