# Generated by Django 2.1.7 on 2020-03-18 02:58

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200317_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='avatar',
            field=models.ImageField(default='noimage.png', null=True, upload_to=utils.file_upload.professor_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(default='noimage.png', null=True, upload_to=utils.file_upload.university_path, verbose_name='Лого'),
        ),
    ]
