# Generated by Django 2.1.7 on 2020-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_privacypolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorreview',
            name='moderator_message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
