# Generated by Django 2.1.7 on 2020-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Аббревиатура'),
        ),
    ]
