# Generated by Django 2.1.7 on 2020-05-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200517_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorreview',
            name='custom_decline_reason',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Комментарий причины отказа от модератора'),
        ),
        migrations.AddField(
            model_name='professorreview',
            name='decline_reason',
            field=models.CharField(choices=[('Пожалуйста, обновите транскрипт', 'Обновите транскрипт'), ('Пожалуйста, прикрепите транскрипт', 'Прикрепите транскрипт'), ('Модерации не удалось удостоверить ваши данные', 'Не удалось удостоверить данные'), ('Пожалуйста, подтвердите почту', 'Почта не подтверждена'), ('Другая причина', 'Другая причина')], default='Модерации не удалось удостоверить ваши данные', max_length=500, verbose_name='Причина отказа'),
        ),
    ]
