# Generated by Django 2.1.7 on 2020-03-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200328_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='patronymic',
            field=models.CharField(default='', max_length=50, verbose_name='Отчество'),
        ),
    ]
