# Generated by Django 2.1.7 on 2020-03-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200328_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название предмета'),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Аббревиатура'),
        ),
    ]
