# Generated by Django 2.1.7 on 2020-04-30 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_auto_20200328_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='paid_users',
            field=models.ManyToManyField(blank=True, related_name='paid_professors', to=settings.AUTH_USER_MODEL, verbose_name='Список кто может смотреть отзывы'),
        ),
        migrations.AddField(
            model_name='professorrating',
            name='status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Принят', 'Принят'), ('Отказан', 'Отказан')], default='На модерации', max_length=100, verbose_name='Статус'),
        ),
    ]
