# Generated by Django 2.1.7 on 2020-05-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200501_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['id'], 'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
