# Generated by Django 2.1.7 on 2020-05-08 12:25

import authe.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authe.managers.UserManager()),
            ],
        ),
    ]
