# Generated by Django 2.1.7 on 2020-05-10 15:59

from django.db import migrations, models
import utils.file_upload


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_auto_20200508_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to=utils.file_upload.transcript_path, verbose_name='Транскрипт'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
    ]
