# Generated by Django 2.1.7 on 2020-05-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_auto_20200510_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвердил email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
