# Generated by Django 2.1.7 on 2020-03-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200317_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorrating',
            name='value',
        ),
    ]
